"""initial migration

Revision ID: ad0827a1c9d7
Revises: None
Create Date: 2016-09-11 00:01:54.544000

"""

# revision identifiers, used by Alembic.
revision = 'ad0827a1c9d7'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('Table1')
    op.drop_table('sysdiagrams')
    op.drop_table('Student')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('sname', sa.NCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('sex', sa.NCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('bir', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sname', name=u'PK__Student__0F1ED58278C86C61')
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(length='max'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=u'PK__sysdiagr__C2B05B618078E22A')
    )
    op.create_table('Table1',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.NCHAR(length=10), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    ### end Alembic commands ###
